### ISSUE TITLE
[Question] Are there plans to support Windows?

### ISSUE THREAD

**Issue by ansonhorse** [Kwai-Kolors/Kolors#12]
https://github.com/Kwai-Kolors/Kolors/blob/f9c664ca537cc0031f4e54cd504d8a1a3c53e36c/requirements.txt#L2

According to [triton - README](https://github.com/triton-lang/triton?tab=readme-ov-file#compatibility),  it seems that `triton` only supports LInux currently.

And I've tested on Windows 10 ( python 3.8 ):
```log
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton
```

Related issue: https://github.com/triton-lang/triton/issues/1640

**Comment by s9anus98a** [comment]
Use open source operating system we don't support closed source

**Comment by huwenkai26** [comment]
我在win11 python 3.10 上面安装成功了
pip install https://huggingface.co/r4ziel/xformers_pre_built/resolve/main/triton-2.0.0-cp310-cp310-win_amd64.whl

**Comment by maybleMyers** [comment]
I got it to run on WSL using windows 10.

You can also run it on windows with comfyui.
