### ISSUE TITLE
kolors with clip text encoder

### ISSUE THREAD

**Issue by YongtaoGe** [Kwai-Kolors/Kolors#16]
Hi, authors. Is there a plan to release the model pre-trained with the CLIP text encoder? Although Chat-GLM gets impressive results, the model is too heavy for tasks that do not need detailed text descriptions.

Thanks very much.

**Comment by 1091492188** [comment]
maybe you can load 4bit model

**Comment by maybleMyers** [comment]
You would have to retrain the entire model to use clip lol. It would take months and $$$$$$$$$$$$$$

**Comment by lzneu** [comment]
Sorry，we have no plans to release a CLIP version at this time.
