### ISSUE TITLE
我明明已经安装了kolorsmodule，为什么还是不行？

### ISSUE THREAD

**Issue by 1030zero** [Kwai-Kolors/Kolors#45]
![image](https://github.com/user-attachments/assets/4fb649c7-ac06-469c-91ca-388635f9d4c4)

**Comment by mikestut** [comment]
我也一样的问题，会不会是编译过程中出现的问题。

**Comment by JincanDeng** [comment]
@1030zero @mikestut 需要通过源码的方式安装：
```
pip3 uninstall kolors
python3 setup.py install
```

**Comment by mikestut** [comment]
注意新增conda环境，python8是很关键



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月15日(周一) 下午2:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kwai-Kolors/Kolors] 我明明已经安装了kolorsmodule，为什么还是不行？ (Issue #45)




 
@1030zero @mikestut 需要通过源码的方式安装：
 pip3 uninstall kolors python3 setup.py install

**Comment by 1030zero** [comment]
> 我也一样的问题，会不会是编译过程中出现的问题。

![image](https://github.com/user-attachments/assets/90c7ac4c-0e3c-4cef-ab3c-f8bd2cfdc938)
