### ISSUE TITLE
Is gradio interface available?

### ISSUE THREAD

**Issue by ptits** [Kwai-Kolors/Kolors#6]

**Comment by maybleMyers** [comment]
https://github.com/Kwai-Kolors/Kolors/pull/3
or there is a node for comfy

**Comment by Raxephion** [comment]
Busy with one at the moment - should be done by the end of the week :) So far I've done AuraFlow, Lumina. Kolors is next and after that Hunyuan DiT and PixArt Sigma. These gradio web apps are all highly optimised for low VRAM (think 6GB laptops)
