### ISSUE TITLE
怎样只加载 xxx.fp16.safetensors ？

### ISSUE THREAD

**Issue by jkla139** [Kwai-Kolors/Kolors#7]
类似的[问题](https://github.com/Tencent/MimicMotion/issues/3)，
由于存储空间不足，只下载了vae和unetd 的半精度模型，但是搜索不到。,variant="fp16"也无效

```
File ~/miniconda3/lib/python3.10/site-packages/diffusers/models/modeling_utils.py:614, in ModelMixin.from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    612         pass
    613 if model_file is None:
--> 614     model_file = _get_model_file(
    615         pretrained_model_name_or_path,
    616         weights_name=_add_variant(WEIGHTS_NAME, variant),
    617         cache_dir=cache_dir,
    618         force_download=force_download,
    619         resume_download=resume_download,
    620         proxies=proxies,
    621         local_files_only=local_files_only,
    622         token=token,
    623         revision=revision,
    624         subfolder=subfolder,
    625         user_agent=user_agent,
    626         commit_hash=commit_hash,
    627     )
    629 if low_cpu_mem_usage:
    630     # Instantiate model with empty weights
    631     with accelerate.init_empty_weights():

File ~/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py:118, in validate_hf_hub_args.<locals>._inner_fn(*args, **kwargs)
    115 if check_use_auth_token:
    116     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__name__, has_token=has_token, kwargs=kwargs)
--> 118 return fn(*args, **kwargs)

File ~/miniconda3/lib/python3.10/site-packages/diffusers/utils/hub_utils.py:307, in _get_model_file(pretrained_model_name_or_path, weights_name, subfolder, cache_dir, force_download, proxies, resume_download, local_files_only, token, user_agent, revision, commit_hash)
    305         return model_file
    306     else:
--> 307         raise EnvironmentError(
    308             f"Error no file named {weights_name} found in directory {pretrained_model_name_or_path}."
    309         )
    310 else:
    311     # 1. First check if deprecated way of loading from branches is used
    312     if (
    313         revision in DEPRECATED_REVISION_ARGS
    314         and (weights_name == WEIGHTS_NAME or weights_name == SAFETENSORS_WEIGHTS_NAME)
    315         and version.parse(version.parse(__version__).base_version) >= version.parse("0.22.0")
    316     ):

OSError: Error no file named diffusion_pytorch_model.bin found in directory /root/Kolors/weights/Kolors/unet.
```

**Comment by JincanDeng** [comment]
@jkla139 建议参考 https://github.com/Kwai-Kolors/Kolors/blob/master/scripts/sample.py 进行模型的初始化。当前还不支持直接通过 pipeline 的 from_pretrained 函数进行初始化，相关功能正在开发中。

**Comment by JincanDeng** [comment]
@jkla139 模型在 fp16 下进行 batch size=1 的推理，大概需要 20G 显存，可以参考下。

**Comment by jkla139** [comment]
> @jkla139 建议参考 https://github.com/Kwai-Kolors/Kolors/blob/master/scripts/sample.py 进行模型的初始化。当前还不支持直接通过 pipeline 的 from_pretrained 函数进行初始化，相关功能正在开发中。

但是`sample.py`里面的代码即使不通过 pipeline 的 from_pretrained 函数加载模型也无法找到 diffusion_pytorch_model.fp16.safetensors
```
vae = AutoencoderKL.from_pretrained(f"{ckpt_dir}/vae", revision=None).half()
unet = UNet2DConditionModel.from_pretrained(f"{ckpt_dir}/unet", revision=None).half()
```
![image](https://github.com/Kwai-Kolors/Kolors/assets/44624598/0a3ef4ff-d1fe-479f-8997-149b809670aa)

**Comment by chuck-ma** [comment]
可以参考我下面的代码：

`from kolors.pipelines.pipeline_stable_diffusion_xl_chatglm_256 import StableDiffusionXLPipeline
from kolors.models.modeling_chatglm import ChatGLMModel
from kolors.models.tokenization_chatglm import ChatGLMTokenizer
from diffusers import UNet2DConditionModel, AutoencoderKL
from diffusers import EulerDiscreteScheduler
from huggingface_hub import snapshot_download
import torch
import os


# Download the model files
ckpt_dir = snapshot_download(repo_id="Kwai-Kolors/Kolors", ignore_patterns=[
    "vae/diffusion_pytorch_model.fp16.bin",
    "vae/diffusion_pytorch_model.bin",
    "unet/diffusion_pytorch_model.safetensors",
    "vae/diffusion_pytorch_model.safetensors",
])


# Load the models
text_encoder = ChatGLMModel.from_pretrained(
    os.path.join(ckpt_dir, 'text_encoder'),
    torch_dtype=torch.float16).half()
tokenizer = ChatGLMTokenizer.from_pretrained(
    os.path.join(ckpt_dir, 'text_encoder'))
vae = AutoencoderKL.from_pretrained(
    os.path.join(ckpt_dir, "vae"),  variant="fp16").half()
scheduler = EulerDiscreteScheduler.from_pretrained(
    os.path.join(ckpt_dir, "scheduler"))
unet = UNet2DConditionModel.from_pretrained(
    os.path.join(ckpt_dir, "unet"), variant="fp16").half()

pipe = StableDiffusionXLPipeline(
    vae=vae,
    text_encoder=text_encoder,
    tokenizer=tokenizer,
    unet=unet,
    scheduler=scheduler,
    force_zeros_for_empty_prompt=False)
pipe.enable_model_cpu_offload()`

**Comment by lichtud** [comment]
unet = UNet2DConditionModel.from_pretrained(f"{ckpt_dir}/unet", revision=None).half()修改代码为unet = UNet2DConditionModel.from_pretrained(f"{ckpt_dir}/unet", revision=None, torch_dtype=torch.float16, variant='fp16')
