### ISSUE TITLE
关于controlnet的模型文件

### ISSUE THREAD

**Issue by ldqrecord** [Kwai-Kolors/Kolors#83]
![image](https://github.com/user-attachments/assets/3381360c-8566-49d2-9ea0-9b82496bdea8)
![image](https://github.com/user-attachments/assets/8975d0b0-c241-49ec-baa6-e6a43d8f7411)
执行 sample_controlNet_ipadapter.py 会提示没有bin模型，然后fp16模型，这个有吗

**Comment by junqiangwu** [comment]
> ![image](https://private-user-images.githubusercontent.com/75522836/352540045-3381360c-8566-49d2-9ea0-9b82496bdea8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTA0OTMsIm5iZiI6MTcyMjA5MDE5MywicGF0aCI6Ii83NTUyMjgzNi8zNTI1NDAwNDUtMzM4MTM2MGMtODU2Ni00OWQyLTllYTAtOWI4MjQ5NmJkZWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE0MjMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZmU1NTEzZGEyOWIyMTA0ZDk0ODIwZWM0MWUzOTEyNzVkMWMzN2JhZWQyZGJkYzcyYzMyNTNiMWQ0NmViMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yVBUiXCkYdIwmWu6SFt_mnlP6bQEz7AZ8BQ7H9AK73Y) ![image](https://private-user-images.githubusercontent.com/75522836/352540109-8975d0b0-c241-49ec-baa6-e6a43d8f7411.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTA0OTMsIm5iZiI6MTcyMjA5MDE5MywicGF0aCI6Ii83NTUyMjgzNi8zNTI1NDAxMDktODk3NWQwYjAtYzI0MS00OWVjLWJhYTYtZTZhNDNkOGY3NDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE0MjMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MTNmNzkwMGU5NWEwY2M0NmIzOGQ1MDMyMDdmNWIxYmFiMDkxYzUxYmQxNDcyNDA5ZjVkMDM5NDQ5ZjJjMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wxynOFxlhDYIYRHEcrPC3ofgq52SMYBs9VNPRWAfttc) 执行 sample_controlNet_ipadapter.py 会提示没有bin模型，然后fp16模型，这个有吗

Please confirm that the version of diffusers you have used is consistent with the requirements of kolors.

**Comment by ldqrecord** [comment]
还原模型名解决了
