### ISSUE TITLE
官方能不能出一个webui，集合controlnet、ipadapter 和 inpainting 的功能？

### ISSUE THREAD

**Issue by wodsoe** [Kwai-Kolors/Kolors#85]
官方能不能出一个webui，集合controlnet、ipadapter 和 inpainting 的功能？

**Comment by theoldsong** [comment]
+1

**Comment by JoshonSmith** [comment]
有社区支持的comfyui

**Comment by YacratesWyh** [comment]
> 有社区支持的comfyui

comfy现在用的wrapper相当于直接跑kolor代码，不支持ipa inpainting这些。

**Comment by YacratesWyh** [comment]
https://github.com/MinusZoneAI/ComfyUI-Kolors-MZ
brilliant works here
